version: '3'

services:

  back-end:
    build:
      context: ./../back-end
      dockerfile: ./../back-end/back-end.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1

  admin-service:
    build:
      context: ./../admin-service
      dockerfile: ./../admin-service/admin-service.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
  
  mongo:
    image: 'mongo:4.2.16-bionic'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db